# Generated by Django 5.2.17 on 2026-08-28 16:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CaseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("narrative", models.TextField()),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_fa", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("sort_order", "name_en"),
            },
        ),
        migrations.CreateModel(
            name="ClinicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("patient_summary", models.TextField()),
                ("educational_objective", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("introductory", "Introductory"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="introductory",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("citation", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "publication_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("source_type", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("name_en", models.CharField(max_length=220)),
                ("name_fa", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("cognitive", "Cognitive"),
                            ("emotional", "Emotional"),
                            ("behavioral", "Behavioral"),
                            ("somatic", "Somatic"),
                            ("interpersonal", "Interpersonal"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("max_score", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="atlas.clinicalcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("score_value", models.IntegerField(default=0)),
                ("feedback", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="atlas.casequestion",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="casequestion",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="atlas.casestep",
            ),
        ),
        migrations.AddField(
            model_name="casestep",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="atlas.clinicalcase",
            ),
        ),
        migrations.CreateModel(
            name="Disorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("name_en", models.CharField(max_length=220)),
                ("name_fa", models.CharField(blank=True, max_length=220)),
                ("short_description", models.TextField(blank=True)),
                ("overview", models.TextField(blank=True)),
                ("clinical_features", models.TextField(blank=True)),
                ("risk_factors", models.TextField(blank=True)),
                ("treatment_overview", models.TextField(blank=True)),
                ("assessment_overview", models.TextField(blank=True)),
                ("typical_onset", models.CharField(blank=True, max_length=220)),
                ("course_note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disorders",
                        to="atlas.category",
                    ),
                ),
            ],
            options={
                "ordering": ("name_en",),
            },
        ),
        migrations.CreateModel(
            name="DifferentialRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("differential", "Differential"),
                            ("related", "Related"),
                            ("commonly_confused", "Commonly confused"),
                        ],
                        max_length=32,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "related_disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="atlas.disorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="primary_disorder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinical_cases",
                to="atlas.disorder",
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="atlas.disorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="atlas.disorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="atlas.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="atlas.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuizChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="atlas.quizquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="atlas.quizattempt",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.quizchoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.quizquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisorderSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disorder_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisorderSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prominence",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("common", "Common"),
                            ("possible", "Possible"),
                            ("contextual", "Contextual"),
                        ],
                        default="common",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_links",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disorder_links",
                        to="atlas.symptom",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseAttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_score", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="atlas.caseattempt",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.casechoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.casequestion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "question"), name="uq_case_attempt_question"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="casestep",
            constraint=models.UniqueConstraint(
                fields=("case", "sort_order"), name="uq_case_step_order"
            ),
        ),
        migrations.AddIndex(
            model_name="caseattempt",
            index=models.Index(
                fields=["user", "status"], name="atlas_casea_user_id_523201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseattempt",
            index=models.Index(
                fields=["user", "-created_at"], name="atlas_casea_user_id_0d8c1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disorder",
            index=models.Index(
                fields=["category", "is_active"], name="atlas_disor_categor_f273b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disorder",
            index=models.Index(
                fields=["name_en"], name="atlas_disor_name_en_0aed7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disorder",
            index=models.Index(
                fields=["name_fa"], name="atlas_disor_name_fa_563ffe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrelationship",
            constraint=models.UniqueConstraint(
                fields=("disorder", "related_disorder", "relationship_type"),
                name="uq_disorder_relationship",
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("disorder", models.F("related_disorder")), _negated=True
                ),
                name="ck_relationship_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "disorder"), name="uq_user_disorder_bookmark"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["user", "status"], name="atlas_quiza_user_id_733159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["user", "-created_at"], name="atlas_quiza_user_id_bca2fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattemptanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uq_quiz_attempt_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="disordersource",
            constraint=models.UniqueConstraint(
                fields=("disorder", "source"), name="uq_disorder_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="disordersymptom",
            constraint=models.UniqueConstraint(
                fields=("disorder", "symptom"), name="uq_disorder_symptom"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "disorder"), name="uq_user_disorder_progress"
            ),
        ),
    ]
