# Generated by Django 5.2.17 on 2026-08-28 18:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0002_usernote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("name_en", models.CharField(max_length=220)),
                ("name_fa", models.CharField(blank=True, max_length=220)),
                ("simple_definition", models.TextField()),
                ("academic_definition", models.TextField(blank=True)),
                ("example", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical"),
                            ("cognitive", "Cognitive"),
                            ("behavioral", "Behavioral"),
                            ("emotional", "Emotional"),
                            ("assessment", "Assessment"),
                            ("treatment", "Treatment"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name_en",),
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active"], name="atlas_conce_kind_81ad62_idx"
                    ),
                    models.Index(
                        fields=["name_en"], name="atlas_conce_name_en_853231_idx"
                    ),
                    models.Index(
                        fields=["name_fa"], name="atlas_conce_name_fa_c00973_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_challenges",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_challenges",
                        to="atlas.disorder",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="DailyChallengeChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="atlas.dailychallenge",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("hint", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="basic",
                        max_length=24,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flashcards",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flashcards",
                        to="atlas.disorder",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="StudyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("disorder_view", "Disorder view"),
                            ("concept_view", "Concept view"),
                            ("quiz_completed", "Quiz completed"),
                            ("case_completed", "Case completed"),
                            ("flashcard_review", "Flashcard review"),
                            ("daily_challenge", "Daily challenge"),
                            ("note_saved", "Note saved"),
                            ("bookmark_saved", "Bookmark saved"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "clinical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_activities",
                        to="atlas.clinicalcase",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_activities",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_activities",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "flashcard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_activities",
                        to="atlas.flashcard",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_activities",
                        to="atlas.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="UserConceptProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="atlas.concept",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFlashcardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("learning", "Learning"),
                            ("review", "Review"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                (
                    "ease_factor",
                    models.FloatField(
                        default=2.5,
                        validators=[
                            django.core.validators.MinValueValidator(1.3),
                            django.core.validators.MaxValueValidator(4.0),
                        ],
                    ),
                ),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                (
                    "last_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("again", "Again"),
                            ("hard", "Hard"),
                            ("good", "Good"),
                            ("easy", "Easy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="atlas.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="atlas.concept",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "concept"), name="uq_user_concept_bookmark"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConceptNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notes",
                        to="atlas.concept",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "concept"), name="uq_user_concept_note"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConceptRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("part_of", "Part of"),
                            ("maintains", "Maintains"),
                            ("influences", "Influences"),
                            ("contrasts", "Contrasts with"),
                            ("applied_in", "Applied in"),
                        ],
                        default="related",
                        max_length=32,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "source_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_concept_relationships",
                        to="atlas.concept",
                    ),
                ),
                (
                    "target_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_concept_relationships",
                        to="atlas.concept",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_concept",
                            "target_concept",
                            "relationship_type",
                        ),
                        name="uq_concept_relationship",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_concept", models.F("target_concept")),
                            _negated=True,
                        ),
                        name="ck_concept_relationship_not_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.concept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concept_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("concept", "source"), name="uq_concept_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyChallengeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_date", models.DateField()),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="atlas.dailychallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenge_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.dailychallengechoice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-activity_date"],
                        name="atlas_daily_user_id_41a31f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "activity_date"),
                        name="uq_user_daily_challenge_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DisorderConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("associated", "Associated"),
                            ("maintaining", "Maintaining"),
                            ("assessment", "Assessment"),
                            ("treatment", "Treatment"),
                            ("differential", "Differential"),
                        ],
                        default="associated",
                        max_length=32,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disorder_links",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_links",
                        to="atlas.disorder",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("disorder", "concept", "role"),
                        name="uq_disorder_concept_role",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["is_active", "difficulty"],
                name="atlas_flash_is_acti_92024e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studyactivity",
            index=models.Index(
                fields=["user", "-occurred_at"], name="atlas_study_user_id_0fc7db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyactivity",
            index=models.Index(
                fields=["user", "activity_type"], name="atlas_study_user_id_c07ebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconceptprogress",
            index=models.Index(
                fields=["user", "progress_percent"],
                name="atlas_userc_user_id_d0abb4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userconceptprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "concept"), name="uq_user_concept_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="userflashcardprogress",
            index=models.Index(
                fields=["user", "due_at"], name="atlas_userf_user_id_e60f37_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userflashcardprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "flashcard"), name="uq_user_flashcard_progress"
            ),
        ),
    ]
