# Generated by Django 5.2.17 on 2026-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0003_concept_dailychallenge_dailychallengechoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="kind",
            field=models.CharField(
                choices=[
                    ("clinical", "Clinical"),
                    ("cognitive", "Cognitive"),
                    ("behavioral", "Behavioral"),
                    ("emotional", "Emotional"),
                    ("interpersonal", "Interpersonal"),
                    ("assessment", "Assessment"),
                    ("treatment", "Treatment"),
                    ("general", "General"),
                ],
                default="general",
                max_length=32,
            ),
        ),
    ]
