# Generated by Django 5.2.17 on 2026-08-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0004_alter_concept_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSMCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("version_name", models.CharField(blank=True, max_length=300)),
                ("version_date", models.DateField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=80)),
                ("purpose", models.TextField(blank=True)),
                ("copyright_note", models.TextField(blank=True)),
                ("clinical_note", models.TextField(blank=True)),
                ("source_filename", models.CharField(max_length=500)),
                ("source_sha256", models.CharField(db_index=True, max_length=64)),
                ("official_status", models.JSONField(blank=True, default=dict)),
                ("source_registry", models.JSONField(blank=True, default=dict)),
                ("quality_audit", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("study_guide", models.JSONField(blank=True, default=list)),
                ("urgent_warnings", models.JSONField(blank=True, default=dict)),
                ("cultural_note", models.TextField(blank=True)),
                ("periodic_review", models.JSONField(blank=True, default=list)),
                ("release_updates", models.JSONField(blank=True, default=dict)),
                ("health_check", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_document", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-version_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="DSMRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("master_id", models.CharField(db_index=True, max_length=40)),
                ("sort_index", models.PositiveIntegerField(default=0)),
                (
                    "root_section",
                    models.CharField(blank=True, db_index=True, max_length=180),
                ),
                (
                    "chapter_number",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("chapter_name_fa", models.CharField(blank=True, max_length=300)),
                ("chapter_name_en", models.CharField(blank=True, max_length=300)),
                ("group_name", models.CharField(blank=True, max_length=300)),
                (
                    "name_fa",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                (
                    "name_en",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("source_type", models.CharField(blank=True, max_length=200)),
                (
                    "classification_status",
                    models.CharField(blank=True, db_index=True, max_length=300),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("diagnosis", "Diagnosis"),
                            ("structural", "Structural"),
                            ("clinical_attention", "Clinical attention"),
                            ("research", "Research condition"),
                            ("alternative_model", "Alternative model"),
                            ("specifier", "Specifier"),
                            ("reference", "Structural reference"),
                            ("code", "Additional code"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                ("specialization_level", models.CharField(blank=True, max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("key_features", models.JSONField(blank=True, default=list)),
                ("assessment", models.JSONField(blank=True, default=list)),
                ("differential", models.JSONField(blank=True, default=list)),
                ("comorbidity", models.TextField(blank=True)),
                ("course", models.TextField(blank=True)),
                ("management", models.JSONField(blank=True, default=list)),
                ("assessment_tools", models.JSONField(blank=True, default=list)),
                ("context_considerations", models.TextField(blank=True)),
                ("red_flags", models.TextField(blank=True)),
                ("pitfalls", models.JSONField(blank=True, default=list)),
                ("nearby_titles", models.JSONField(blank=True, default=list)),
                ("official_updates", models.JSONField(blank=True, default=list)),
                ("homonym_info", models.JSONField(blank=True, default=dict)),
                ("prevalence_numeric", models.JSONField(blank=True, null=True)),
                ("prevalence_policy", models.TextField(blank=True)),
                ("coding", models.TextField(blank=True)),
                ("source_keys", models.JSONField(blank=True, default=list)),
                ("quality", models.JSONField(blank=True, default=dict)),
                ("exam_tip", models.TextField(blank=True)),
                ("self_test", models.JSONField(blank=True, default=list)),
                ("structural_path", models.JSONField(blank=True, default=dict)),
                ("search_text", models.TextField(blank=True)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="atlas.dsmcorpus",
                    ),
                ),
                (
                    "linked_disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsm_master_records",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="atlas.dsmrecord",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_index", "master_id"),
                "indexes": [
                    models.Index(
                        fields=["corpus", "display_type", "sort_index"],
                        name="atlas_dsmre_corpus__c7f3e4_idx",
                    ),
                    models.Index(
                        fields=["corpus", "chapter_number", "sort_index"],
                        name="atlas_dsmre_corpus__5f9bb4_idx",
                    ),
                    models.Index(
                        fields=["linked_disorder", "is_active"],
                        name="atlas_dsmre_linked__94cb9f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("corpus", "master_id"), name="uq_dsm_corpus_master_id"
                    )
                ],
            },
        ),
    ]
