# Generated by Django 5.2.17 on 2026-08-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0005_dsmcorpus_dsmrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSMRecordRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("nearby", "Nearby title"),
                            ("differential", "Differential title"),
                        ],
                        max_length=24,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dsm_relations",
                        to="atlas.dsmrecord",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dsm_relations",
                        to="atlas.dsmrecord",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "source__sort_index",
                    "target__sort_index",
                    "relationship_type",
                ),
                "indexes": [
                    models.Index(
                        fields=["source", "relationship_type"],
                        name="atlas_dsmre_source__94ab59_idx",
                    ),
                    models.Index(
                        fields=["target", "relationship_type"],
                        name="atlas_dsmre_target__4b3d7e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target", "relationship_type"),
                        name="uq_dsm_record_relation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source", models.F("target")), _negated=True
                        ),
                        name="ck_dsm_record_relation_not_self",
                    ),
                ],
            },
        ),
    ]
