# Generated by Django 5.2.17 on 2026-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0006_dsmrecordrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="disorder",
            name="data_origin",
            field=models.CharField(
                choices=[("curated", "Curated Atlas"), ("dsm_master", "DSM MASTER")],
                db_index=True,
                default="curated",
                max_length=24,
            ),
        ),
    ]
