# Generated by Django 5.2.17 on 2026-08-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0007_disorder_data_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=220)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fa", "Persian"),
                            ("en", "English"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("abbreviation", "Abbreviation"),
                            ("historical", "Historical"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
            },
        ),
        migrations.CreateModel(
            name="ConceptRelationshipSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("associated", "Associated"),
                            ("manifestation", "Manifestation"),
                            ("overlaps_with", "Overlaps with"),
                            ("contrasts", "Contrasts with"),
                        ],
                        default="associated",
                        max_length=32,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ConceptSymptomSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="concept",
            name="common_confusions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="counterexample",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="domain",
            field=models.CharField(
                choices=[
                    ("psychopathology", "Psychopathology"),
                    ("cognitive_psychology", "Cognitive Psychology"),
                    ("cbt", "Cognitive Behavioral Therapy"),
                    ("behavioral_science", "Behavioral Science"),
                    ("emotion", "Emotion"),
                    ("interpersonal", "Interpersonal"),
                    ("assessment", "Assessment"),
                    ("general", "General Psychology"),
                ],
                db_index=True,
                default="general",
                max_length=48,
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="recognition_cues",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="subtype",
            field=models.CharField(
                choices=[
                    ("general", "General concept"),
                    ("cognitive_distortion", "Cognitive distortion"),
                ],
                db_index=True,
                default="general",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="conceptrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("part_of", "Part of"),
                    ("subtype_of", "Subtype of"),
                    ("prerequisite", "Prerequisite"),
                    ("maintains", "Maintains"),
                    ("influences", "Influences"),
                    ("mechanism", "Mechanism"),
                    ("contrasts", "Contrasts with"),
                    ("commonly_confused_with", "Commonly confused with"),
                    ("associated_with", "Associated with"),
                    ("applied_in", "Applied in"),
                ],
                default="related",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(
                fields=["domain", "is_active"], name="atlas_conce_domain_054b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(
                fields=["subtype", "is_active"], name="atlas_conce_subtype_5ed990_idx"
            ),
        ),
        migrations.AddField(
            model_name="conceptalias",
            name="concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="atlas.concept",
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationshipsource",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_links",
                to="atlas.conceptrelationship",
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationshipsource",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="concept_relationship_links",
                to="atlas.sourcereference",
            ),
        ),
        migrations.AddField(
            model_name="conceptsymptom",
            name="concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="symptom_links",
                to="atlas.concept",
            ),
        ),
        migrations.AddField(
            model_name="conceptsymptom",
            name="symptom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="concept_links",
                to="atlas.symptom",
            ),
        ),
        migrations.AddField(
            model_name="conceptsymptomsource",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_links",
                to="atlas.conceptsymptom",
            ),
        ),
        migrations.AddField(
            model_name="conceptsymptomsource",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="concept_symptom_links",
                to="atlas.sourcereference",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptalias",
            index=models.Index(fields=["text"], name="atlas_conce_text_fb447d_idx"),
        ),
        migrations.AddConstraint(
            model_name="conceptalias",
            constraint=models.UniqueConstraint(
                fields=("concept", "text", "language"), name="uq_concept_alias"
            ),
        ),
        migrations.AddConstraint(
            model_name="conceptrelationshipsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_concept_relationship_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="conceptsymptom",
            constraint=models.UniqueConstraint(
                fields=("concept", "symptom", "relationship_type"),
                name="uq_concept_symptom",
            ),
        ),
        migrations.AddConstraint(
            model_name="conceptsymptomsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_concept_symptom_source"
            ),
        ),
    ]
