# Generated by Django 5.2.17 on 2026-08-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0008_conceptalias_conceptrelationshipsource_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("disorder_view", "Disorder view"),
                    ("concept_view", "Concept view"),
                    ("quiz_completed", "Quiz completed"),
                    ("case_completed", "Case completed"),
                    ("flashcard_review", "Flashcard review"),
                    ("daily_challenge", "Daily challenge"),
                    ("distortion_practice", "Cognitive distortion practice"),
                    ("note_saved", "Note saved"),
                    ("bookmark_saved", "Bookmark saved"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CognitiveDistortionPracticeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("prompt", models.TextField()),
                ("explanation", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="basic",
                        max_length=24,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_concept",
                    models.ForeignKey(
                        limit_choices_to={"subtype": "cognitive_distortion"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distortion_practice_items",
                        to="atlas.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CognitiveDistortionPracticeChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("is_correct", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distortion_practice_choices",
                        to="atlas.concept",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="atlas.cognitivedistortionpracticeitem",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CognitiveDistortionPracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_correct", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distortion_practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="atlas.cognitivedistortionpracticechoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="atlas.cognitivedistortionpracticeitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="cognitivedistortionpracticeitem",
            index=models.Index(
                fields=["is_active", "difficulty"],
                name="atlas_cogni_is_acti_4e7b2e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cognitivedistortionpracticechoice",
            constraint=models.UniqueConstraint(
                fields=("item", "concept"), name="uq_distortion_practice_item_concept"
            ),
        ),
        migrations.AddIndex(
            model_name="cognitivedistortionpracticeattempt",
            index=models.Index(
                fields=["user", "-created_at"], name="atlas_cogni_user_id_57831c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cognitivedistortionpracticeattempt",
            index=models.Index(
                fields=["user", "is_correct"], name="atlas_cogni_user_id_6b26ed_idx"
            ),
        ),
    ]
