# Generated by Django 5.2.17 on 2026-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0010_cognitivedistortionpracticechoice_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="casechoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="casequestion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="casestep",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dailychallengechoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quizchoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
