# Generated by Django 5.2.17 on 2026-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0011_content_children_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalcase",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cognitivedistortionpracticeitem",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
    ]
