# Generated by Django 5.2.17 on 2026-09-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0012_seed_managed_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("academic_definition", models.TextField(blank=True)),
                ("historical_context", models.TextField(blank=True)),
                ("core_principles", models.TextField(blank=True)),
                ("typical_structure", models.TextField(blank=True)),
                ("appropriate_contexts", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("safety_notes", models.TextField(blank=True)),
                ("evidence_note", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name_en",),
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("academic_definition", models.TextField(blank=True)),
                ("application_notes", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("safety_notes", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name_en",),
                "indexes": [
                    models.Index(
                        fields=["review_status", "is_active"],
                        name="atlas_techn_review__dde5b7_idx",
                    ),
                    models.Index(
                        fields=["name_en"], name="atlas_techn_name_en_69bcbb_idx"
                    ),
                    models.Index(
                        fields=["name_fa"], name="atlas_techn_name_fa_2b8568_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("targets", "Targets"),
                            ("addresses", "Addresses"),
                            ("teaches", "Teaches"),
                            ("mechanism", "Mechanism"),
                            ("applied_to", "Applied to"),
                        ],
                        max_length=24,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_links",
                        to="atlas.concept",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_links",
                        to="atlas.technique",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TechniqueConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.techniqueconcept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_concept_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechniqueSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_links",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.technique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapyAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fa", "Persian"),
                            ("en", "English"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("abbreviation", "Abbreviation"),
                            ("historical", "Historical"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
            },
        ),
        migrations.CreateModel(
            name="TherapyClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name_en", models.CharField(max_length=220)),
                ("name_fa", models.CharField(blank=True, max_length=220)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("focus", "Focus"),
                            ("method", "Method"),
                            ("delivery", "Delivery"),
                            ("population", "Population"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("kind", "sort_order", "name_en"),
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active"], name="atlas_thera_kind_1e80c6_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TherapyClassificationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_links",
                        to="atlas.therapyclassification",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TherapyConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("targets", "Targets"),
                            ("uses", "Uses"),
                            ("addresses", "Addresses"),
                            ("teaches", "Teaches"),
                            ("mechanism", "Mechanism"),
                            ("applied_to", "Applied to"),
                        ],
                        max_length=24,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_links",
                        to="atlas.concept",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TherapyConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.therapyconcept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_concept_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapyDisorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinical_role",
                    models.CharField(
                        choices=[
                            ("unspecified", "Unspecified"),
                            ("guideline_recommended", "Guideline recommended"),
                            ("commonly_used", "Commonly used"),
                            ("adjunctive", "Adjunctive"),
                            ("alternative", "Alternative"),
                            ("context_dependent", "Context dependent"),
                            ("not_first_line", "Not first line"),
                            ("research_context", "Research context"),
                        ],
                        db_index=True,
                        default="unspecified",
                        max_length=32,
                    ),
                ),
                (
                    "evidence_basis",
                    models.CharField(
                        choices=[
                            ("not_assessed", "Not assessed"),
                            ("guideline", "Guideline"),
                            ("systematic_review", "Systematic review / meta-analysis"),
                            ("controlled_trials", "Controlled trials"),
                            ("observational", "Observational evidence"),
                            ("mixed", "Mixed evidence"),
                            ("emerging", "Emerging evidence"),
                            ("insufficient", "Insufficient evidence"),
                        ],
                        db_index=True,
                        default="not_assessed",
                        max_length=32,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("evidence_note", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_links",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disorder_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TherapyDisorderSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.therapydisorder",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_disorder_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapyFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name_en", models.CharField(max_length=220)),
                ("name_fa", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("sort_order", "name_en"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="atlas_thera_is_acti_313d8a_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="therapy",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="therapies",
                to="atlas.therapyfamily",
            ),
        ),
        migrations.CreateModel(
            name="TherapySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_links",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapyTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("common", "Common"),
                            ("optional", "Optional"),
                            ("adapted", "Adapted"),
                            ("component", "Component"),
                        ],
                        default="common",
                        max_length=24,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_links",
                        to="atlas.technique",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TherapyTechniqueSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.therapytechnique",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_technique_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechniqueAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fa", "Persian"),
                            ("en", "English"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("abbreviation", "Abbreviation"),
                            ("historical", "Historical"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="atlas.technique",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
                "indexes": [
                    models.Index(fields=["text"], name="atlas_techn_text_8a7847_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "text", "language"),
                        name="uq_technique_alias",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="techniqueconcept",
            index=models.Index(
                fields=["technique", "is_active"], name="atlas_techn_techniq_2bdaaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techniqueconcept",
            index=models.Index(
                fields=["concept", "is_active"], name="atlas_techn_concept_e2f7a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="techniqueconcept",
            constraint=models.UniqueConstraint(
                fields=("technique", "concept", "relationship_type"),
                name="uq_technique_concept_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="techniqueconceptsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_technique_concept_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="techniquesource",
            constraint=models.UniqueConstraint(
                fields=("technique", "source"), name="uq_technique_source"
            ),
        ),
        migrations.AddIndex(
            model_name="therapyalias",
            index=models.Index(fields=["text"], name="atlas_thera_text_57c1e5_idx"),
        ),
        migrations.AddConstraint(
            model_name="therapyalias",
            constraint=models.UniqueConstraint(
                fields=("therapy", "text", "language"), name="uq_therapy_alias"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapyclassificationlink",
            constraint=models.UniqueConstraint(
                fields=("therapy", "classification"), name="uq_therapy_classification"
            ),
        ),
        migrations.AddIndex(
            model_name="therapyconcept",
            index=models.Index(
                fields=["therapy", "is_active"], name="atlas_thera_therapy_32fa3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapyconcept",
            index=models.Index(
                fields=["concept", "is_active"], name="atlas_thera_concept_6afe4b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapyconcept",
            constraint=models.UniqueConstraint(
                fields=("therapy", "concept", "relationship_type"),
                name="uq_therapy_concept_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="therapyconceptsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_therapy_concept_source"
            ),
        ),
        migrations.AddIndex(
            model_name="therapydisorder",
            index=models.Index(
                fields=["therapy", "is_active"], name="atlas_thera_therapy_f641db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapydisorder",
            index=models.Index(
                fields=["disorder", "is_active"], name="atlas_thera_disorde_9dcedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapydisorder",
            index=models.Index(
                fields=["evidence_basis", "is_active"],
                name="atlas_thera_evidenc_cb8c5c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="therapydisorder",
            constraint=models.UniqueConstraint(
                fields=("therapy", "disorder"), name="uq_therapy_disorder"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapydisordersource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_therapy_disorder_source"
            ),
        ),
        migrations.AddIndex(
            model_name="therapy",
            index=models.Index(
                fields=["family", "is_active"], name="atlas_thera_family__53122a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapy",
            index=models.Index(
                fields=["review_status", "is_active"],
                name="atlas_thera_review__3869e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="therapy",
            index=models.Index(
                fields=["name_en"], name="atlas_thera_name_en_7c39b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapy",
            index=models.Index(
                fields=["name_fa"], name="atlas_thera_name_fa_89c065_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapysource",
            constraint=models.UniqueConstraint(
                fields=("therapy", "source"), name="uq_therapy_source"
            ),
        ),
        migrations.AddIndex(
            model_name="therapytechnique",
            index=models.Index(
                fields=["therapy", "is_active"], name="atlas_thera_therapy_b1a6fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapytechnique",
            constraint=models.UniqueConstraint(
                fields=("therapy", "technique"), name="uq_therapy_technique"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapytechniquesource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_therapy_technique_source"
            ),
        ),
    ]
