# Generated by Django 5.2.17 on 2026-09-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0014_studyactivity_therapy_therapybookmark_therapynote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=180, unique=True)),
                ("source_filename", models.CharField(max_length=500)),
                (
                    "source_sha256",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("dataset_name", models.CharField(blank=True, max_length=300)),
                ("dataset_version", models.CharField(blank=True, max_length=120)),
                ("generated_at_text", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("statistics", models.JSONField(blank=True, default=dict)),
                ("quality_control", models.JSONField(blank=True, default=dict)),
                ("raw_document", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ResearchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section", models.CharField(db_index=True, max_length=64)),
                ("external_id", models.CharField(max_length=300)),
                (
                    "canonical_key",
                    models.CharField(blank=True, db_index=True, max_length=400),
                ),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("name_en", models.CharField(blank=True, max_length=500)),
                ("name_fa", models.CharField(blank=True, max_length=500)),
                ("source_ids", models.JSONField(blank=True, default=list)),
                (
                    "verification_status",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "review_status",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "promoted_model",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("promoted_pk", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("dataset_id", "section", "id"),
            },
        ),
        migrations.AddField(
            model_name="sourcereference",
            name="authors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sourcereference",
            name="doi",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sourcereference",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sourcereference",
            name="pmid",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sourcereference",
            name="verification_status",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="sourcereference",
            name="url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name="sourcereference",
            index=models.Index(fields=["title"], name="atlas_sourc_title_3fb1ed_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcereference",
            index=models.Index(
                fields=["publication_year"], name="atlas_sourc_publica_4c8bfb_idx"
            ),
        ),
        migrations.AddField(
            model_name="researchrecord",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="atlas.researchdataset",
            ),
        ),
        migrations.AddIndex(
            model_name="researchrecord",
            index=models.Index(
                fields=["section", "canonical_key"],
                name="atlas_resea_section_4bdde7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchrecord",
            index=models.Index(
                fields=["promoted_model", "promoted_pk"],
                name="atlas_resea_promote_258979_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrecord",
            constraint=models.UniqueConstraint(
                fields=("dataset", "section", "external_id"),
                name="uq_research_dataset_section_external_id",
            ),
        ),
    ]
