# Generated by Django 5.2.17 on 2026-09-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0015_researchdataset_researchrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="techniqueconcept",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapyclassificationlink",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapyconcept",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapydisorder",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapytechnique",
            name="seed_managed",
            field=models.BooleanField(default=False),
        ),
    ]
