# Generated by Django 5.2.17 on 2026-09-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0016_techniqueconcept_seed_managed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchdataset",
            name="ingestion_audit",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="researchdataset",
            name="raw_text",
            field=models.TextField(blank=True),
        ),
    ]
