# Generated by Django 5.2.17 on 2026-09-05 02:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0017_researchdataset_ingestion_audit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Psychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("summary_en", models.TextField(blank=True)),
                ("summary_fa", models.TextField(blank=True)),
                ("role_en", models.CharField(blank=True, max_length=180)),
                ("role_fa", models.CharField(blank=True, max_length=180)),
                ("nationality_en", models.CharField(blank=True, max_length=180)),
                ("nationality_fa", models.CharField(blank=True, max_length=180)),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "death_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("academic_disciplines", models.JSONField(blank=True, default=list)),
                ("contributions_en", models.JSONField(blank=True, default=list)),
                ("contributions_fa", models.JSONField(blank=True, default=list)),
                ("affiliations", models.JSONField(blank=True, default=list)),
                ("historical_context_en", models.TextField(blank=True)),
                ("historical_context_fa", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name_en",),
                "indexes": [
                    models.Index(
                        fields=["review_status", "is_active"],
                        name="atlas_psych_review__27045b_idx",
                    ),
                    models.Index(
                        fields=["name_en"], name="atlas_psych_name_en_529a21_idx"
                    ),
                    models.Index(
                        fields=["name_fa"], name="atlas_psych_name_fa_e58455_idx"
                    ),
                    models.Index(
                        fields=["birth_year"], name="atlas_psych_birth_y_2f16d5_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("death_year__isnull", True),
                            ("birth_year__isnull", True),
                            ("death_year__gte", models.F("birth_year")),
                            _connector="OR",
                        ),
                        name="ck_psychologist_life_year_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PsychologistConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("originated", "Originated"),
                            ("proposed", "Proposed"),
                            ("co_proposed", "Co-proposed"),
                            ("developed", "Developed"),
                            ("co_developed", "Co-developed"),
                            ("expanded", "Expanded"),
                            ("popularized", "Popularized"),
                            ("researched", "Researched"),
                            ("applied", "Applied"),
                            ("contributed_to", "Contributed to"),
                            ("criticized", "Criticized"),
                            ("challenged", "Challenged"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychologist_links",
                        to="atlas.concept",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_links",
                        to="atlas.psychologist",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PsychologistConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.psychologistconcept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychologist_concept_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologistPsychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("collaborated_with", "Collaborated with"),
                            ("influenced", "Influenced"),
                            ("mentored", "Mentored"),
                            ("criticized", "Criticized"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_psychologist_links",
                        to="atlas.psychologist",
                    ),
                ),
                (
                    "related_psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_psychologist_links",
                        to="atlas.psychologist",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PsychologistPsychologistSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.psychologistpsychologist",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychologist_psychologist_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologistSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("biography", "Biography"),
                            ("primary_work", "Primary work"),
                            ("institutional", "Institutional biography/archive"),
                            ("historical_review", "Historical review"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.psychologist",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychologist_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologistTheory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("originated", "Originated"),
                            ("proposed", "Proposed"),
                            ("co_proposed", "Co-proposed"),
                            ("developed", "Developed"),
                            ("co_developed", "Co-developed"),
                            ("expanded", "Expanded"),
                            ("popularized", "Popularized"),
                            ("researched", "Researched"),
                            ("applied", "Applied"),
                            ("contributed_to", "Contributed to"),
                            ("criticized", "Criticized"),
                            ("challenged", "Challenged"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_links",
                        to="atlas.psychologist",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PsychologistTheorySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.psychologisttheory",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychologist_theory_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologistTherapy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("originated", "Originated"),
                            ("proposed", "Proposed"),
                            ("co_proposed", "Co-proposed"),
                            ("developed", "Developed"),
                            ("co_developed", "Co-developed"),
                            ("expanded", "Expanded"),
                            ("popularized", "Popularized"),
                            ("researched", "Researched"),
                            ("applied", "Applied"),
                            ("contributed_to", "Contributed to"),
                            ("criticized", "Criticized"),
                            ("challenged", "Challenged"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_links",
                        to="atlas.psychologist",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychologist_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PsychologistTherapySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.psychologisttherapy",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychologist_therapy_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("domain", models.CharField(blank=True, db_index=True, max_length=160)),
                ("period_text", models.CharField(blank=True, max_length=180)),
                ("summary_en", models.TextField(blank=True)),
                ("summary_fa", models.TextField(blank=True)),
                ("core_proposition_en", models.TextField(blank=True)),
                ("core_proposition_fa", models.TextField(blank=True)),
                ("historical_context_en", models.TextField(blank=True)),
                ("historical_context_fa", models.TextField(blank=True)),
                ("key_propositions_en", models.JSONField(blank=True, default=list)),
                ("key_propositions_fa", models.JSONField(blank=True, default=list)),
                ("applications_en", models.JSONField(blank=True, default=list)),
                ("applications_fa", models.JSONField(blank=True, default=list)),
                ("criticisms_en", models.JSONField(blank=True, default=list)),
                ("criticisms_fa", models.JSONField(blank=True, default=list)),
                ("limitations_en", models.JSONField(blank=True, default=list)),
                ("limitations_fa", models.JSONField(blank=True, default=list)),
                (
                    "modern_status",
                    models.CharField(blank=True, db_index=True, max_length=180),
                ),
                ("historical_importance_en", models.TextField(blank=True)),
                ("historical_importance_fa", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name_en",),
                "indexes": [
                    models.Index(
                        fields=["domain", "is_active"],
                        name="atlas_theor_domain_ecbd16_idx",
                    ),
                    models.Index(
                        fields=["review_status", "is_active"],
                        name="atlas_theor_review__19d56c_idx",
                    ),
                    models.Index(
                        fields=["name_en"], name="atlas_theor_name_en_7ae6c8_idx"
                    ),
                    models.Index(
                        fields=["name_fa"], name="atlas_theor_name_fa_92f573_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="psychologisttheory",
            name="theory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="psychologist_links",
                to="atlas.theory",
            ),
        ),
        migrations.CreateModel(
            name="TheoryAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fa", "Persian"),
                            ("en", "English"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("abbreviation", "Abbreviation"),
                            ("historical", "Historical"),
                            ("transliteration", "Transliteration"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="atlas.theory",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
            },
        ),
        migrations.CreateModel(
            name="TheoryConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("grounds", "Grounds"),
                            ("informs", "Informs"),
                            ("supports", "Supports"),
                            ("complements", "Complements"),
                            ("challenges", "Challenges"),
                            ("challenged_by", "Challenged by"),
                            ("reformulated_as", "Reformulated as"),
                            (
                                "supports_interpretation_of",
                                "Supports interpretation of",
                            ),
                            ("extends", "Extends"),
                            ("refines", "Refines"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_links",
                        to="atlas.concept",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_links",
                        to="atlas.theory",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TheoryConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.theoryconcept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theory_concept_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TheorySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary_publication", "Primary publication"),
                            ("historical_review", "Historical review"),
                            ("evidence_review", "Evidence review"),
                            ("institutional", "Institutional source"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theory_links",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.theory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TheoryTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("grounds", "Grounds"),
                            ("informs", "Informs"),
                            ("supports", "Supports"),
                            ("complements", "Complements"),
                            ("challenges", "Challenges"),
                            ("challenged_by", "Challenged by"),
                            ("reformulated_as", "Reformulated as"),
                            (
                                "supports_interpretation_of",
                                "Supports interpretation of",
                            ),
                            ("extends", "Extends"),
                            ("refines", "Refines"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_links",
                        to="atlas.technique",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_links",
                        to="atlas.theory",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TheoryTechniqueSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.theorytechnique",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theory_technique_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TheoryTheory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("grounds", "Grounds"),
                            ("informs", "Informs"),
                            ("supports", "Supports"),
                            ("complements", "Complements"),
                            ("challenges", "Challenges"),
                            ("challenged_by", "Challenged by"),
                            ("reformulated_as", "Reformulated as"),
                            (
                                "supports_interpretation_of",
                                "Supports interpretation of",
                            ),
                            ("extends", "Extends"),
                            ("refines", "Refines"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "related_theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_theory_links",
                        to="atlas.theory",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_theory_links",
                        to="atlas.theory",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TheoryTheorySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.theorytheory",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theory_theory_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TheoryTherapy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("grounds", "Grounds"),
                            ("informs", "Informs"),
                            ("supports", "Supports"),
                            ("complements", "Complements"),
                            ("challenges", "Challenges"),
                            ("challenged_by", "Challenged by"),
                            ("reformulated_as", "Reformulated as"),
                            (
                                "supports_interpretation_of",
                                "Supports interpretation of",
                            ),
                            ("extends", "Extends"),
                            ("refines", "Refines"),
                            ("associated_with", "Associated with"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_links",
                        to="atlas.theory",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TheoryTherapySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.theorytherapy",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theory_therapy_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("subject", "Subject"),
                            ("author", "Author"),
                            ("developer", "Developer"),
                            ("publication", "Publication"),
                            ("institutional", "Institutional"),
                            ("context", "Context"),
                        ],
                        default="related",
                        max_length=24,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_links",
                        to="atlas.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimelineConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.timelineconcept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_concept_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("title_en", models.CharField(max_length=500)),
                ("title_fa", models.CharField(blank=True, max_length=500)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("historical_importance_en", models.TextField(blank=True)),
                ("historical_importance_fa", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("publication", "Publication"),
                            ("theory_development", "Theory development"),
                            ("therapy_development", "Therapy development"),
                            ("research_finding", "Research finding"),
                            ("institutional", "Institutional milestone"),
                            ("professional", "Professional milestone"),
                            ("classification", "Classification / nosology"),
                            ("guideline", "Guideline"),
                            ("other", "Other"),
                            ("unspecified", "Unspecified"),
                        ],
                        db_index=True,
                        default="unspecified",
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("exact_date", "Exact date"),
                            ("year", "Year only"),
                            ("year_range", "Year range"),
                            ("approximate_year", "Approximate year"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("date_text", models.CharField(blank=True, max_length=180)),
                (
                    "year_start",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "year_end",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("exact_date", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("year_start", "exact_date", "id"),
                "indexes": [
                    models.Index(
                        fields=["year_start", "is_active"],
                        name="atlas_timel_year_st_773ef8_idx",
                    ),
                    models.Index(
                        fields=["event_type", "is_active"],
                        name="atlas_timel_event_t_62dfdb_idx",
                    ),
                    models.Index(
                        fields=["review_status", "is_active"],
                        name="atlas_timel_review__860961_idx",
                    ),
                    models.Index(
                        fields=["title_en"], name="atlas_timel_title_e_b604c5_idx"
                    ),
                    models.Index(
                        fields=["title_fa"], name="atlas_timel_title_f_fca205_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("year_end__isnull", True),
                            ("year_start__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_timeline_end_requires_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("year_end__isnull", True),
                            ("year_end__gte", models.F("year_start")),
                            _connector="OR",
                        ),
                        name="ck_timeline_year_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("date_precision", "exact_date"), _negated=True),
                            ("exact_date__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_timeline_exact_requires_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("date_precision", "exact_date"),
                            ("exact_date__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_timeline_nonexact_has_no_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "date_precision__in",
                                    ("year", "year_range", "approximate_year"),
                                ),
                                _negated=True,
                            ),
                            ("year_start__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_timeline_year_precision_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("date_precision", "year_range"), _negated=True),
                            ("year_end__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_timeline_range_requires_end",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="timelineconcept",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concept_links",
                to="atlas.timelineevent",
            ),
        ),
        migrations.CreateModel(
            name="TimelineEventSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary source"),
                            ("historical_review", "Historical review"),
                            ("institutional", "Institutional source"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.timelineevent",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_event_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelinePsychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("subject", "Subject"),
                            ("author", "Author"),
                            ("developer", "Developer"),
                            ("publication", "Publication"),
                            ("institutional", "Institutional"),
                            ("context", "Context"),
                        ],
                        default="related",
                        max_length=24,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychologist_links",
                        to="atlas.timelineevent",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_links",
                        to="atlas.psychologist",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimelinePsychologistSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.timelinepsychologist",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_psychologist_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineTheory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("subject", "Subject"),
                            ("author", "Author"),
                            ("developer", "Developer"),
                            ("publication", "Publication"),
                            ("institutional", "Institutional"),
                            ("context", "Context"),
                        ],
                        default="related",
                        max_length=24,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_links",
                        to="atlas.timelineevent",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_links",
                        to="atlas.theory",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimelineTheorySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.timelinetheory",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_theory_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineTherapy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("subject", "Subject"),
                            ("author", "Author"),
                            ("developer", "Developer"),
                            ("publication", "Publication"),
                            ("institutional", "Institutional"),
                            ("context", "Context"),
                        ],
                        default="related",
                        max_length=24,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_links",
                        to="atlas.timelineevent",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_links",
                        to="atlas.therapy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimelineTherapySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.timelinetherapy",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_therapy_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologistAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fa", "Persian"),
                            ("en", "English"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("initials", "Initials"),
                            ("transliteration", "Transliteration"),
                            ("historical", "Historical"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="atlas.psychologist",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
                "indexes": [
                    models.Index(fields=["text"], name="atlas_psych_text_409058_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("psychologist", "text", "language"),
                        name="uq_psychologist_alias",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="psychologistconcept",
            index=models.Index(
                fields=["psychologist", "is_active"],
                name="atlas_psych_psychol_d6cb42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="psychologistconcept",
            index=models.Index(
                fields=["concept", "is_active"], name="atlas_psych_concept_c79cc2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologistconcept",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "concept", "relationship_type"),
                name="uq_psychologist_concept_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologistconceptsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_psychologist_concept_source"
            ),
        ),
        migrations.AddIndex(
            model_name="psychologistpsychologist",
            index=models.Index(
                fields=["psychologist", "is_active"],
                name="atlas_psych_psychol_6e52da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="psychologistpsychologist",
            index=models.Index(
                fields=["related_psychologist", "is_active"],
                name="atlas_psych_related_7e9a43_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologistpsychologist",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "related_psychologist", "relationship_type"),
                name="uq_psychologist_psychologist_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologistpsychologist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("psychologist", models.F("related_psychologist")), _negated=True
                ),
                name="ck_psychologist_relation_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologistpsychologistsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"),
                name="uq_psychologist_psychologist_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologistsource",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "source", "role"), name="uq_psychologist_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologisttheorysource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_psychologist_theory_source"
            ),
        ),
        migrations.AddIndex(
            model_name="psychologisttherapy",
            index=models.Index(
                fields=["psychologist", "is_active"],
                name="atlas_psych_psychol_7d46a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="psychologisttherapy",
            index=models.Index(
                fields=["therapy", "is_active"], name="atlas_psych_therapy_1d3816_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologisttherapy",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "therapy", "relationship_type"),
                name="uq_psychologist_therapy_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologisttherapysource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_psychologist_therapy_source"
            ),
        ),
        migrations.AddIndex(
            model_name="psychologisttheory",
            index=models.Index(
                fields=["psychologist", "is_active"],
                name="atlas_psych_psychol_fe6cd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="psychologisttheory",
            index=models.Index(
                fields=["theory", "is_active"], name="atlas_psych_theory__7569fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="psychologisttheory",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "theory", "relationship_type"),
                name="uq_psychologist_theory_relation",
            ),
        ),
        migrations.AddIndex(
            model_name="theoryalias",
            index=models.Index(fields=["text"], name="atlas_theor_text_6c02b9_idx"),
        ),
        migrations.AddConstraint(
            model_name="theoryalias",
            constraint=models.UniqueConstraint(
                fields=("theory", "text", "language"), name="uq_theory_alias"
            ),
        ),
        migrations.AddIndex(
            model_name="theoryconcept",
            index=models.Index(
                fields=["theory", "is_active"], name="atlas_theor_theory__37e991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="theoryconcept",
            index=models.Index(
                fields=["concept", "is_active"], name="atlas_theor_concept_afdb98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="theoryconcept",
            constraint=models.UniqueConstraint(
                fields=("theory", "concept", "relationship_type"),
                name="uq_theory_concept_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="theoryconceptsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_theory_concept_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="theorysource",
            constraint=models.UniqueConstraint(
                fields=("theory", "source", "role"), name="uq_theory_source"
            ),
        ),
        migrations.AddIndex(
            model_name="theorytechnique",
            index=models.Index(
                fields=["theory", "is_active"], name="atlas_theor_theory__4850a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="theorytechnique",
            index=models.Index(
                fields=["technique", "is_active"], name="atlas_theor_techniq_ac7e61_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytechnique",
            constraint=models.UniqueConstraint(
                fields=("theory", "technique", "relationship_type"),
                name="uq_theory_technique_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytechniquesource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_theory_technique_source"
            ),
        ),
        migrations.AddIndex(
            model_name="theorytheory",
            index=models.Index(
                fields=["theory", "is_active"], name="atlas_theor_theory__17ddba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="theorytheory",
            index=models.Index(
                fields=["related_theory", "is_active"],
                name="atlas_theor_related_cb083b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytheory",
            constraint=models.UniqueConstraint(
                fields=("theory", "related_theory", "relationship_type"),
                name="uq_theory_theory_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytheory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("theory", models.F("related_theory")), _negated=True
                ),
                name="ck_theory_relation_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytheorysource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_theory_theory_source"
            ),
        ),
        migrations.AddIndex(
            model_name="theorytherapy",
            index=models.Index(
                fields=["theory", "is_active"], name="atlas_theor_theory__9ac8f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="theorytherapy",
            index=models.Index(
                fields=["therapy", "is_active"], name="atlas_theor_therapy_75007e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytherapy",
            constraint=models.UniqueConstraint(
                fields=("theory", "therapy", "relationship_type"),
                name="uq_theory_therapy_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="theorytherapysource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_theory_therapy_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelineconceptsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_timeline_concept_source"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineconcept",
            index=models.Index(
                fields=["event", "is_active"], name="atlas_timel_event_i_ff5895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineconcept",
            index=models.Index(
                fields=["concept", "is_active"], name="atlas_timel_concept_b94dac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelineconcept",
            constraint=models.UniqueConstraint(
                fields=("event", "concept", "role"), name="uq_timeline_concept"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelineeventsource",
            constraint=models.UniqueConstraint(
                fields=("event", "source", "role"), name="uq_timeline_event_source"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinepsychologist",
            index=models.Index(
                fields=["event", "is_active"], name="atlas_timel_event_i_67f654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinepsychologist",
            index=models.Index(
                fields=["psychologist", "is_active"],
                name="atlas_timel_psychol_fdc562_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinepsychologist",
            constraint=models.UniqueConstraint(
                fields=("event", "psychologist", "role"),
                name="uq_timeline_psychologist",
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinepsychologistsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"),
                name="uq_timeline_psychologist_source",
            ),
        ),
        migrations.AddIndex(
            model_name="timelinetheory",
            index=models.Index(
                fields=["event", "is_active"], name="atlas_timel_event_i_b89487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinetheory",
            index=models.Index(
                fields=["theory", "is_active"], name="atlas_timel_theory__8c4588_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinetheory",
            constraint=models.UniqueConstraint(
                fields=("event", "theory", "role"), name="uq_timeline_theory"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinetheorysource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_timeline_theory_source"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinetherapy",
            index=models.Index(
                fields=["event", "is_active"], name="atlas_timel_event_i_111402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinetherapy",
            index=models.Index(
                fields=["therapy", "is_active"], name="atlas_timel_therapy_8105fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinetherapy",
            constraint=models.UniqueConstraint(
                fields=("event", "therapy", "role"), name="uq_timeline_therapy"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinetherapysource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_timeline_therapy_source"
            ),
        ),
    ]
