# Generated by Django 5.2.17 on 2026-09-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0018_v061_psychologists_theories_timeline_foundation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologistconcept",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("originated", "Originated"),
                    ("proposed", "Proposed"),
                    ("co_proposed", "Co-proposed"),
                    ("developed", "Developed"),
                    ("co_developed", "Co-developed"),
                    (
                        "developed_or_majorly_associated_with",
                        "Developed or majorly associated with",
                    ),
                    ("expanded", "Expanded"),
                    ("popularized", "Popularized"),
                    ("researched", "Researched"),
                    ("researched_or_developed", "Researched or developed"),
                    ("applied", "Applied"),
                    ("contributed_to", "Contributed to"),
                    ("criticized", "Criticized"),
                    ("challenged", "Challenged"),
                    ("associated_with", "Associated with"),
                    ("majorly_associated_with", "Majorly associated with"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="psychologisttheory",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("originated", "Originated"),
                    ("proposed", "Proposed"),
                    ("co_proposed", "Co-proposed"),
                    ("developed", "Developed"),
                    ("co_developed", "Co-developed"),
                    (
                        "developed_or_majorly_associated_with",
                        "Developed or majorly associated with",
                    ),
                    ("expanded", "Expanded"),
                    ("popularized", "Popularized"),
                    ("researched", "Researched"),
                    ("researched_or_developed", "Researched or developed"),
                    ("applied", "Applied"),
                    ("contributed_to", "Contributed to"),
                    ("criticized", "Criticized"),
                    ("challenged", "Challenged"),
                    ("associated_with", "Associated with"),
                    ("majorly_associated_with", "Majorly associated with"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="psychologisttherapy",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("originated", "Originated"),
                    ("proposed", "Proposed"),
                    ("co_proposed", "Co-proposed"),
                    ("developed", "Developed"),
                    ("co_developed", "Co-developed"),
                    (
                        "developed_or_majorly_associated_with",
                        "Developed or majorly associated with",
                    ),
                    ("expanded", "Expanded"),
                    ("popularized", "Popularized"),
                    ("researched", "Researched"),
                    ("researched_or_developed", "Researched or developed"),
                    ("applied", "Applied"),
                    ("contributed_to", "Contributed to"),
                    ("criticized", "Criticized"),
                    ("challenged", "Challenged"),
                    ("associated_with", "Associated with"),
                    ("majorly_associated_with", "Majorly associated with"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="theoryconcept",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("grounds", "Grounds"),
                    ("includes_construct", "Includes construct"),
                    ("informs", "Informs"),
                    ("supports", "Supports"),
                    ("complements", "Complements"),
                    ("challenges", "Challenges"),
                    ("challenged_by", "Challenged by"),
                    ("reformulated_as", "Reformulated as"),
                    ("supports_interpretation_of", "Supports interpretation of"),
                    ("extends", "Extends"),
                    ("refines", "Refines"),
                    ("associated_with", "Associated with"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="theorytechnique",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("grounds", "Grounds"),
                    ("includes_construct", "Includes construct"),
                    ("informs", "Informs"),
                    ("supports", "Supports"),
                    ("complements", "Complements"),
                    ("challenges", "Challenges"),
                    ("challenged_by", "Challenged by"),
                    ("reformulated_as", "Reformulated as"),
                    ("supports_interpretation_of", "Supports interpretation of"),
                    ("extends", "Extends"),
                    ("refines", "Refines"),
                    ("associated_with", "Associated with"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="theorytheory",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("grounds", "Grounds"),
                    ("includes_construct", "Includes construct"),
                    ("informs", "Informs"),
                    ("supports", "Supports"),
                    ("complements", "Complements"),
                    ("challenges", "Challenges"),
                    ("challenged_by", "Challenged by"),
                    ("reformulated_as", "Reformulated as"),
                    ("supports_interpretation_of", "Supports interpretation of"),
                    ("extends", "Extends"),
                    ("refines", "Refines"),
                    ("associated_with", "Associated with"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="theorytherapy",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("grounds", "Grounds"),
                    ("includes_construct", "Includes construct"),
                    ("informs", "Informs"),
                    ("supports", "Supports"),
                    ("complements", "Complements"),
                    ("challenges", "Challenges"),
                    ("challenged_by", "Challenged by"),
                    ("reformulated_as", "Reformulated as"),
                    ("supports_interpretation_of", "Supports interpretation of"),
                    ("extends", "Extends"),
                    ("refines", "Refines"),
                    ("associated_with", "Associated with"),
                ],
                max_length=40,
            ),
        ),
    ]
