# Generated by Django 5.2.17 on 2026-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0019_v062_research_promotion_semantics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineconcept",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="timelinepsychologist",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="timelinetheory",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="timelinetherapy",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=24,
            ),
        ),
    ]
