# Generated by Django 5.2.17 on 2026-09-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0020_v062_timeline_relation_semantics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineconcept",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("marks_therapy_milestone", "Marks therapy milestone"),
                    (
                        "marks_technique_evidence_milestone",
                        "Marks technique evidence milestone",
                    ),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="timelinepsychologist",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("marks_therapy_milestone", "Marks therapy milestone"),
                    (
                        "marks_technique_evidence_milestone",
                        "Marks technique evidence milestone",
                    ),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="timelinetheory",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("marks_therapy_milestone", "Marks therapy milestone"),
                    (
                        "marks_technique_evidence_milestone",
                        "Marks technique evidence milestone",
                    ),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="timelinetherapy",
            name="role",
            field=models.CharField(
                choices=[
                    ("related", "Related"),
                    ("involves_person", "Involves person"),
                    ("marks_theory_milestone", "Marks theory milestone"),
                    ("marks_therapy_milestone", "Marks therapy milestone"),
                    (
                        "marks_technique_evidence_milestone",
                        "Marks technique evidence milestone",
                    ),
                    ("subject", "Subject"),
                    ("author", "Author"),
                    ("developer", "Developer"),
                    ("publication", "Publication"),
                    ("institutional", "Institutional"),
                    ("context", "Context"),
                ],
                default="related",
                max_length=48,
            ),
        ),
        migrations.CreateModel(
            name="TimelineTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("involves_person", "Involves person"),
                            ("marks_theory_milestone", "Marks theory milestone"),
                            ("marks_therapy_milestone", "Marks therapy milestone"),
                            (
                                "marks_technique_evidence_milestone",
                                "Marks technique evidence milestone",
                            ),
                            ("subject", "Subject"),
                            ("author", "Author"),
                            ("developer", "Developer"),
                            ("publication", "Publication"),
                            ("institutional", "Institutional"),
                            ("context", "Context"),
                        ],
                        default="related",
                        max_length=48,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_links",
                        to="atlas.timelineevent",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_links",
                        to="atlas.technique",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimelineTechniqueSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="atlas.timelinetechnique",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_technique_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="timelinetechnique",
            index=models.Index(
                fields=["event", "is_active"], name="atlas_timel_event_i_0727c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinetechnique",
            index=models.Index(
                fields=["technique", "is_active"], name="atlas_timel_techniq_990f44_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinetechnique",
            constraint=models.UniqueConstraint(
                fields=("event", "technique", "role"), name="uq_timeline_technique"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelinetechniquesource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_timeline_technique_source"
            ),
        ),
    ]
