# Generated by Django 5.2.17 on 2026-09-12 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_case_revisions(apps, schema_editor):
    ClinicalCase = apps.get_model("atlas", "ClinicalCase")
    CaseRevision = apps.get_model("atlas", "CaseRevision")
    CaseStep = apps.get_model("atlas", "CaseStep")
    CaseTransition = apps.get_model("atlas", "CaseTransition")
    CaseAttempt = apps.get_model("atlas", "CaseAttempt")

    for case in ClinicalCase.objects.all().iterator():
        revision = CaseRevision.objects.create(
            case_id=case.id,
            version=1,
            status="published",
            content_hash="",
            published_at=case.updated_at,
            seed_managed=case.seed_managed,
        )
        steps = list(CaseStep.objects.filter(case_id=case.id).order_by("sort_order", "id"))
        for index, step in enumerate(steps, start=1):
            step.revision_id = revision.id
            step.stable_key = f"step-{step.sort_order or index}"
            step.node_kind = "decision"
            step.save(update_fields=("revision", "stable_key", "node_kind"))

        active_steps = [step for step in steps if step.is_active]
        if active_steps:
            revision.entry_step_id = active_steps[0].id
            revision.save(update_fields=("entry_step",))

        for index, step in enumerate(active_steps):
            next_step = active_steps[index + 1] if index + 1 < len(active_steps) else None
            questions = step.questions.filter(is_active=True).order_by("sort_order", "id")
            for question in questions:
                for choice in question.choices.filter(is_active=True).order_by("sort_order", "id"):
                    CaseTransition.objects.create(
                        revision_id=revision.id,
                        source_step_id=step.id,
                        choice_id=choice.id,
                        target_step_id=next_step.id if next_step else None,
                        outcome="continue" if next_step else "complete",
                        sort_order=choice.sort_order,
                        is_active=True,
                        seed_managed=case.seed_managed,
                    )

        case.current_revision_id = revision.id
        case.structure_mode = "linear"
        case.save(update_fields=("current_revision", "structure_mode"))
        CaseAttempt.objects.filter(case_id=case.id, revision__isnull=True).update(revision_id=revision.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0021_v062_timeline_therapy_technique_semantics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=24,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("case_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="CaseTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("continue", "Continue"), ("complete", "Complete")],
                        default="continue",
                        max_length=24,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("source_step__sort_order", "sort_order", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="casestep",
            name="uq_case_step_order",
        ),
        migrations.AddField(
            model_name="casestep",
            name="node_kind",
            field=models.CharField(
                choices=[
                    ("decision", "Decision"),
                    ("information", "Information"),
                    ("terminal", "Terminal"),
                ],
                default="decision",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="casestep",
            name="stable_key",
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="structure_mode",
            field=models.CharField(
                choices=[("linear", "Linear"), ("branching", "Branching")],
                db_index=True,
                default="linear",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="caserevision",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="atlas.clinicalcase",
            ),
        ),
        migrations.AddField(
            model_name="caserevision",
            name="entry_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entry_for_revisions",
                to="atlas.casestep",
            ),
        ),
        migrations.AddField(
            model_name="caseattempt",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="atlas.caserevision",
            ),
        ),
        migrations.AddField(
            model_name="casestep",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="steps",
                to="atlas.caserevision",
            ),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_cases",
                to="atlas.caserevision",
            ),
        ),
        migrations.AddIndex(
            model_name="caseattempt",
            index=models.Index(
                fields=["case", "revision", "status"],
                name="atlas_casea_case_id_23598c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casestep",
            index=models.Index(
                fields=["case", "revision", "is_active"],
                name="atlas_cases_case_id_453ca2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="casestep",
            constraint=models.UniqueConstraint(
                fields=("revision", "stable_key"), name="uq_case_revision_step_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="casestep",
            constraint=models.UniqueConstraint(
                fields=("revision", "sort_order"), name="uq_case_revision_step_order"
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="choice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branch_transition",
                to="atlas.casechoice",
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions",
                to="atlas.caserevision",
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="source_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="atlas.casestep",
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="target_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transitions",
                to="atlas.casestep",
            ),
        ),
        migrations.RunPython(backfill_case_revisions, noop_reverse),
        migrations.AddIndex(
            model_name="caserevision",
            index=models.Index(
                fields=["case", "status"], name="atlas_caser_case_id_122a0e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="caserevision",
            constraint=models.UniqueConstraint(
                fields=("case", "version"), name="uq_case_revision_version"
            ),
        ),
        migrations.AddIndex(
            model_name="casetransition",
            index=models.Index(
                fields=["revision", "source_step", "is_active"],
                name="atlas_caset_revisio_885aa2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="casetransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "continue"), ("target_step__isnull", False)),
                    models.Q(("outcome", "complete"), ("target_step__isnull", True)),
                    _connector="OR",
                ),
                name="ck_case_transition_target_by_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="casetransition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("choice__isnull", True), ("is_active", True)),
                fields=("revision", "source_step"),
                name="uq_active_case_auto_transition",
            ),
        ),
    ]
