# Generated by Django 5.2.17 on 2026-09-12 07:50

import django.db.models.deletion
from django.db import migrations, models


def populate_revision_snapshots(apps, schema_editor):
    CaseRevision = apps.get_model("atlas", "CaseRevision")
    for revision in CaseRevision.objects.select_related("case").iterator():
        case = revision.case
        revision.title = case.title
        revision.patient_summary = case.patient_summary
        revision.educational_objective = case.educational_objective
        revision.difficulty = case.difficulty
        revision.primary_disorder_id = case.primary_disorder_id
        revision.save(update_fields=(
            "title",
            "patient_summary",
            "educational_objective",
            "difficulty",
            "primary_disorder",
        ))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0022_v071_branching_case_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="caserevision",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("introductory", "Introductory"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="introductory",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="caserevision",
            name="educational_objective",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="caserevision",
            name="patient_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="caserevision",
            name="primary_disorder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinical_case_revisions",
                to="atlas.disorder",
            ),
        ),
        migrations.AddField(
            model_name="caserevision",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_revision_snapshots, noop_reverse),
    ]
