# Generated by Django 5.2.17 on 2026-09-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0023_v071_case_revision_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseattempt",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="atlas.caserevision",
            ),
        ),
        migrations.AlterField(
            model_name="casestep",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="steps",
                to="atlas.caserevision",
            ),
        ),
        migrations.AlterField(
            model_name="casestep",
            name="stable_key",
            field=models.SlugField(max_length=120),
        ),
    ]
