# Generated by Django 5.2.17 on 2026-09-12 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_attempt_current_step(apps, schema_editor):
    CaseAttempt = apps.get_model("atlas", "CaseAttempt")
    for attempt in CaseAttempt.objects.filter(status="in_progress", current_step__isnull=True).select_related("revision__entry_step"):
        if attempt.revision.entry_step_id:
            attempt.current_step_id = attempt.revision.entry_step_id
            attempt.save(update_fields=("current_step",))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0024_v071_case_revision_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAttemptEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("decision", "Decision"),
                            ("advance", "Advance"),
                            ("terminal_complete", "Terminal complete"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("continue", "Continue"), ("complete", "Complete")],
                        max_length=24,
                    ),
                ),
                ("awarded_score", models.IntegerField(default=0)),
                ("max_score", models.IntegerField(default=0)),
                ("state_version_before", models.PositiveIntegerField()),
                ("state_version_after", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="caseattempt",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_attempts",
                to="atlas.casestep",
            ),
        ),
        migrations.AddField(
            model_name="caseattempt",
            name="state_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_attempt_current_step, noop_reverse),
        migrations.AddIndex(
            model_name="caseattempt",
            index=models.Index(
                fields=["user", "case", "status"], name="atlas_casea_user_id_e22123_idx"
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="atlas.caseattempt",
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="next_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_attempt_events",
                to="atlas.casestep",
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atlas.casequestion",
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atlas.casechoice",
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt_events",
                to="atlas.casestep",
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="transition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atlas.casetransition",
            ),
        ),
        migrations.AddIndex(
            model_name="caseattemptevent",
            index=models.Index(
                fields=["attempt", "created_at"], name="atlas_casea_attempt_c45bc5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseattemptevent",
            constraint=models.UniqueConstraint(
                fields=("attempt", "step"), name="uq_case_attempt_event_step"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseattemptevent",
            constraint=models.UniqueConstraint(
                fields=("attempt", "state_version_before"),
                name="uq_case_attempt_event_version",
            ),
        ),
    ]
