# Generated by Django 5.2.17 on 2026-09-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0025_v072_attempt_state_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="caserevision",
            name="rubric_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CaseScoringDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stable_key", models.SlugField(max_length=120)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_dimensions",
                        to="atlas.caserevision",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="caseattemptanswer",
            name="scoring_dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt_answers",
                to="atlas.casescoringdimension",
            ),
        ),
        migrations.AddField(
            model_name="caseattemptevent",
            name="scoring_dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt_events",
                to="atlas.casescoringdimension",
            ),
        ),
        migrations.AddField(
            model_name="casequestion",
            name="scoring_dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="atlas.casescoringdimension",
            ),
        ),
        migrations.AddIndex(
            model_name="casescoringdimension",
            index=models.Index(
                fields=["revision", "is_active"], name="atlas_cases_revisio_51f5ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="casescoringdimension",
            constraint=models.UniqueConstraint(
                fields=("revision", "stable_key"),
                name="uq_case_revision_scoring_dimension_key",
            ),
        ),
    ]
