# Generated by Django 5.2.17 on 2026-09-17 20:46

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def reject_duplicate_in_progress_attempts(apps, schema_editor):
    CaseAttempt = apps.get_model("atlas", "CaseAttempt")
    duplicates = list(
        CaseAttempt.objects.filter(status="in_progress")
        .values("user_id", "case_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("user_id", "case_id")[:10]
    )
    if duplicates:
        sample = ", ".join(
            f"user={row['user_id']}/case={row['case_id']}/count={row['total']}"
            for row in duplicates
        )
        raise RuntimeError(
            "Cannot add the active-attempt uniqueness guard while duplicate in-progress "
            f"CaseAttempts exist. Run the Case graph audit and resolve the duplicates first. Sample: {sample}"
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0026_v073_multidimensional_case_scoring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reject_duplicate_in_progress_attempts, noop_reverse),
        migrations.AddConstraint(
            model_name="caseattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")),
                fields=("user", "case"),
                name="uq_case_attempt_user_case_in_progress",
            ),
        ),
    ]
