# Generated by Django 5.2.17 on 2026-09-18 21:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0027_v075_case_attempt_concurrency_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "plan_kind",
                    models.CharField(
                        choices=[("general", "General"), ("exam", "Exam")],
                        db_index=True,
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("generation_version", models.PositiveIntegerField(default=0)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="StudyPlanAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "available_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="atlas.studyplan",
                    ),
                ),
            ],
            options={
                "ordering": ("weekday", "id"),
            },
        ),
        migrations.CreateModel(
            name="StudyPlanScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("include_practice", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "clinical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.clinicalcase",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="atlas.studyplan",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.psychologist",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.quiz",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.theory",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.therapy",
                    ),
                ),
                (
                    "timeline_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_scopes",
                        to="atlas.timelineevent",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="UserStudySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study_timezone",
                    models.CharField(default="Asia/Tehran", max_length=64),
                ),
                (
                    "default_daily_minutes",
                    models.PositiveSmallIntegerField(
                        default=45,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(720),
                        ],
                    ),
                ),
                (
                    "default_session_minutes",
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                (
                    "week_starts_on",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Python weekday convention: Monday=0, Sunday=6.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="studyplan",
            index=models.Index(
                fields=["user", "status"], name="atlas_study_user_id_28a01a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyplan",
            index=models.Index(
                fields=["user", "target_date"], name="atlas_study_user_id_c476bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plan_kind", "general"),
                    ("target_date__isnull", False),
                    _connector="OR",
                ),
                name="ck_study_plan_exam_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_date__isnull", True),
                    ("target_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="ck_study_plan_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanavailability",
            constraint=models.UniqueConstraint(
                fields=("plan", "weekday"), name="uq_study_plan_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="ck_study_availability_weekday",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("available_minutes__gte", 0), ("available_minutes__lte", 1440)
                ),
                name="ck_study_availability_minutes",
            ),
        ),
        migrations.AddIndex(
            model_name="studyplanscope",
            index=models.Index(
                fields=["plan", "priority", "sort_order"],
                name="atlas_study_plan_id_b0d072_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("disorder__isnull", False),
                        ("concept__isnull", True),
                        ("therapy__isnull", True),
                        ("theory__isnull", True),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", False),
                        ("therapy__isnull", True),
                        ("theory__isnull", True),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", True),
                        ("therapy__isnull", False),
                        ("theory__isnull", True),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", True),
                        ("therapy__isnull", True),
                        ("theory__isnull", False),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", True),
                        ("therapy__isnull", True),
                        ("theory__isnull", True),
                        ("psychologist__isnull", False),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", True),
                        ("therapy__isnull", True),
                        ("theory__isnull", True),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", False),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", True),
                        ("therapy__isnull", True),
                        ("theory__isnull", True),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", False),
                        ("clinical_case__isnull", True),
                    ),
                    models.Q(
                        ("disorder__isnull", True),
                        ("concept__isnull", True),
                        ("therapy__isnull", True),
                        ("theory__isnull", True),
                        ("psychologist__isnull", True),
                        ("timeline_event__isnull", True),
                        ("quiz__isnull", True),
                        ("clinical_case__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_study_scope_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 1), ("priority__lte", 5)),
                name="ck_study_scope_priority",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "disorder"), name="uq_study_scope_disorder"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "concept"), name="uq_study_scope_concept"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "therapy"), name="uq_study_scope_therapy"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "theory"), name="uq_study_scope_theory"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "psychologist"), name="uq_study_scope_psychologist"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "timeline_event"), name="uq_study_scope_timeline"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "quiz"), name="uq_study_scope_quiz"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanscope",
            constraint=models.UniqueConstraint(
                fields=("plan", "clinical_case"), name="uq_study_scope_case"
            ),
        ),
        migrations.AddConstraint(
            model_name="userstudysettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_daily_minutes__gte", 5),
                    ("default_daily_minutes__lte", 720),
                ),
                name="ck_study_settings_daily_minutes",
            ),
        ),
        migrations.AddConstraint(
            model_name="userstudysettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_session_minutes__gte", 5),
                    ("default_session_minutes__lte", 240),
                ),
                name="ck_study_settings_session_minutes",
            ),
        ),
        migrations.AddConstraint(
            model_name="userstudysettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_session_minutes__lte", models.F("default_daily_minutes"))
                ),
                name="ck_study_settings_session_lte_daily",
            ),
        ),
        migrations.AddConstraint(
            model_name="userstudysettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("week_starts_on__gte", 0), ("week_starts_on__lte", 6)
                ),
                name="ck_study_settings_week_start",
            ),
        ),
    ]
