# Generated by Django 5.2.17 on 2026-09-19 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0028_v081_study_plan_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyplan",
            name="generation_fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="last_generation_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="StudyBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_kind",
                    models.CharField(
                        choices=[
                            ("flashcard_review", "Flashcard review"),
                            ("concept_review", "Concept review"),
                            ("disorder_review", "Disorder review"),
                            ("therapy_reading", "Therapy reading"),
                            ("theory_reading", "Theory reading"),
                            ("psychologist_reading", "Psychologist reading"),
                            ("timeline_review", "Timeline review"),
                            ("quiz_practice", "Quiz practice"),
                            ("case_practice", "Case practice"),
                            ("distortion_practice", "Cognitive distortion practice"),
                            ("notes_review", "Notes review"),
                            ("daily_challenge_optional", "Daily challenge optional"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("manual", "Manual"),
                            ("recommendation", "Recommendation"),
                        ],
                        db_index=True,
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "estimated_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ]
                    ),
                ),
                ("generation_version", models.PositiveIntegerField(default=0)),
                ("locked_by_user", models.BooleanField(db_index=True, default=False)),
                ("snapshot_title", models.CharField(max_length=255)),
                ("snapshot_subtitle", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.clinicalcase",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="atlas.studyplan",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.psychologist",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.quiz",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks",
                        to="atlas.studyplanscope",
                    ),
                ),
                (
                    "theory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.theory",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.therapy",
                    ),
                ),
                (
                    "timeline_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_blocks",
                        to="atlas.timelineevent",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_date", "sequence", "id"),
                "indexes": [
                    models.Index(
                        fields=["plan", "status", "scheduled_date"],
                        name="atlas_study_plan_id_a036f5_idx",
                    ),
                    models.Index(
                        fields=["plan", "generation_version"],
                        name="atlas_study_plan_id_fa8675_idx",
                    ),
                    models.Index(
                        fields=["plan", "origin", "status"],
                        name="atlas_study_plan_id_1c16bb_idx",
                    ),
                    models.Index(
                        fields=["plan", "scheduled_date", "sequence"],
                        name="atlas_study_plan_id_ef1825_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estimated_minutes__gte", 1),
                            ("estimated_minutes__lte", 1440),
                        ),
                        name="ck_study_block_minutes",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "block_kind__in",
                                    [
                                        "flashcard_review",
                                        "notes_review",
                                        "daily_challenge_optional",
                                    ],
                                ),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "concept_review"),
                                ("concept__isnull", False),
                                ("disorder__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "distortion_practice"),
                                ("concept__isnull", False),
                                ("disorder__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "disorder_review"),
                                ("disorder__isnull", False),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "therapy_reading"),
                                ("therapy__isnull", False),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "theory_reading"),
                                ("theory__isnull", False),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "psychologist_reading"),
                                ("psychologist__isnull", False),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "timeline_review"),
                                ("timeline_event__isnull", False),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("quiz__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "quiz_practice"),
                                ("quiz__isnull", False),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("clinical_case__isnull", True),
                            ),
                            models.Q(
                                ("block_kind", "case_practice"),
                                ("clinical_case__isnull", False),
                                ("disorder__isnull", True),
                                ("concept__isnull", True),
                                ("therapy__isnull", True),
                                ("theory__isnull", True),
                                ("psychologist__isnull", True),
                                ("timeline_event__isnull", True),
                                ("quiz__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_study_block_target_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "in_progress"), _negated=True),
                            ("started_at__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_study_block_in_progress_started",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "completed"), _negated=True),
                            ("completed_at__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_study_block_completed_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "skipped"), _negated=True),
                            ("skipped_at__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_study_block_skipped_at",
                    ),
                ],
            },
        ),
    ]
