# Generated by Django 5.2.17 on 2026-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0029_v082_study_blocks"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studyblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_at__isnull", True),
                    ("status__in", ("in_progress", "completed")),
                    _connector="OR",
                ),
                name="ck_study_block_started_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("status", "completed"),
                    _connector="OR",
                ),
                name="ck_study_block_completed_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="studyblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("skipped_at__isnull", True), ("status", "skipped"), _connector="OR"
                ),
                name="ck_study_block_skipped_status",
            ),
        ),
    ]
