# Generated by Django 5.2.17 on 2026-09-27 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0030_studyblock_ck_study_block_started_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_key", models.CharField(max_length=67)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("overdue_block", "Overdue block"),
                            ("plan_schedule_stale", "Stale plan schedule"),
                            ("plan_generate", "Generate plan schedule"),
                            ("srs_review", "SRS review"),
                            ("plan_capacity", "Plan capacity"),
                            ("case_resume", "Resume case"),
                            ("quiz_retry", "Retry quiz"),
                            ("distortion_practice", "Distortion practice"),
                            ("concept_review", "Concept review"),
                            ("disorder_review", "Disorder review"),
                            ("graph_explore", "Explore graph"),
                            ("srs_start", "Start SRS"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("review_queue", "Review queue"),
                            ("study_plan", "Study plan"),
                            ("study_block", "Study block"),
                            ("quiz", "Quiz"),
                            ("clinical_case", "Clinical case"),
                            ("concept", "Concept"),
                            ("disorder", "Disorder"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("reason_code", models.CharField(max_length=48)),
                ("context_ref", models.CharField(max_length=96)),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not helpful"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("client_event_id", models.UUIDField()),
                ("suppressed_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "recommendation_key", "-created_at", "-id"],
                        name="idx_rec_feedback_latest",
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="idx_rec_feedback_history"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_event_id"),
                        name="uq_recommendation_feedback_event",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("value__in", ("helpful", "not_helpful", "dismissed"))
                        ),
                        name="ck_recommendation_feedback_value",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("value", "dismissed"),
                                ("suppressed_until__isnull", False),
                            ),
                            models.Q(
                                models.Q(("value", "dismissed"), _negated=True),
                                ("suppressed_until__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_recommendation_feedback_suppression",
                    ),
                ],
            },
        ),
    ]
