# Generated by Django 5.2.17 on 2026-09-29 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0031_v083_recommendation_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("block_id_at_start", models.PositiveBigIntegerField()),
                ("client_event_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                (
                    "planned_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ]
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("actual_seconds", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="atlas.studyplan",
                    ),
                ),
                (
                    "primary_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="atlas.studyblock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at", "-id"],
                        name="idx_study_session_user_time",
                    ),
                    models.Index(
                        fields=["plan", "-started_at", "-id"],
                        name="idx_study_session_plan_time",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "in_progress")),
                        fields=("user",),
                        name="uq_study_session_active_user",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "client_event_id"),
                        name="uq_study_session_event",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("block_id_at_start__gt", 0)),
                        name="ck_study_session_block_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("planned_minutes__gte", 5), ("planned_minutes__lte", 240)
                        ),
                        name="ck_study_session_minutes",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actual_seconds__gte", 0), ("actual_seconds__lte", 86400)
                        ),
                        name="ck_study_session_seconds",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("abandoned_at__isnull", True),
                                ("actual_seconds", 0),
                                ("completed_at__isnull", True),
                                ("status", "in_progress"),
                            ),
                            models.Q(
                                ("completed_at__gte", models.F("started_at")),
                                ("completed_at__isnull", False),
                                ("status", "completed"),
                                ("abandoned_at__isnull", True),
                            ),
                            models.Q(
                                ("abandoned_at__gte", models.F("started_at")),
                                ("abandoned_at__isnull", False),
                                ("status", "abandoned"),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_study_session_lifecycle",
                    ),
                ],
            },
        ),
    ]
