# Generated by Django 5.2.17 on 2026-09-29 19:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0032_v084_study_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrainAnatomicalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("whole_brain", "Whole brain"),
                            ("hemisphere", "Hemisphere"),
                            ("lobe", "Lobe"),
                            ("cortical_region", "Cortical region"),
                            ("subcortical_structure", "Subcortical structure"),
                            ("region", "Other region"),
                            ("structure", "Other structure"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "laterality",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("midline", "Midline"),
                            ("bilateral", "Bilateral or unlateralized"),
                            ("not_established", "Not established"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ("name_en", "id"),
                "indexes": [
                    models.Index(
                        fields=["kind", "laterality", "is_active"],
                        name="atlas_brain_kind_8d8bc0_idx",
                    ),
                    models.Index(
                        fields=["review_status", "is_active"],
                        name="atlas_brain_review__4c6839_idx",
                    ),
                    models.Index(
                        fields=["name_en"], name="atlas_brain_name_en_8485c3_idx"
                    ),
                    models.Index(
                        fields=["name_fa"], name="atlas_brain_name_fa_d2b53d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim("slug")
                        ),
                        name="uq_brain_anatomy_slug_ci",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BrainHierarchyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("source_version", models.CharField(max_length=120)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_links",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_links",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BrainHierarchyLinkSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.brainhierarchylink",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_hierarchy_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrainNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("functional_network", "Distributed functional network")
                        ],
                        default="functional_network",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ("name_en", "id"),
                "indexes": [
                    models.Index(
                        fields=["review_status", "is_active"],
                        name="atlas_brain_review__28dd25_idx",
                    ),
                    models.Index(
                        fields=["name_en"], name="atlas_brain_name_en_6056fb_idx"
                    ),
                    models.Index(
                        fields=["name_fa"], name="atlas_brain_name_fa_e8c9a1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim("slug")
                        ),
                        name="uq_brain_network_slug_ci",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BrainExternalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=120)),
                ("identifier", models.CharField(max_length=255)),
                ("source_version", models.CharField(max_length=120)),
                ("url", models.URLField(blank=True, max_length=1000)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identifiers",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_identifier_links",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identifiers",
                        to="atlas.brainnetwork",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrainNetworkAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fa", "Persian")], max_length=12
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("abbreviation", "Abbreviation"),
                            ("historical", "Historical"),
                            ("transliteration", "Transliteration"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="atlas.brainnetwork",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
            },
        ),
        migrations.CreateModel(
            name="BrainNetworkSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.brainnetwork",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_network_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrainAnatomicalAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fa", "Persian")], max_length=12
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("alternative", "Alternative"),
                            ("abbreviation", "Abbreviation"),
                            ("historical", "Historical"),
                            ("transliteration", "Transliteration"),
                        ],
                        default="alternative",
                        max_length=24,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text"),
                "indexes": [
                    models.Index(fields=["text"], name="atlas_brain_text_d8f088_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim("text")
                        ),
                        models.F("entity"),
                        models.F("language"),
                        name="uq_brain_anatomy_alias_ci",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BrainAnatomicalEntitySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_anatomy_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "source"), name="uq_brain_anatomy_source"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="brainhierarchylink",
            index=models.Index(
                fields=["parent", "is_active"], name="atlas_brain_parent__aca283_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brainhierarchylink",
            constraint=models.CheckConstraint(
                condition=models.Q(("child", models.F("parent")), _negated=True),
                name="ck_brain_hierarchy_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainhierarchylink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("child",),
                name="uq_brain_active_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainhierarchylinksource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_brain_hierarchy_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="brainhierarchylinksource",
            constraint=models.CheckConstraint(
                condition=models.Q(("note", ""), _negated=True),
                name="ck_brain_hierarchy_source_note",
            ),
        ),
        migrations.AddIndex(
            model_name="brainexternalidentifier",
            index=models.Index(
                fields=["entity", "namespace"], name="atlas_brain_entity__c4125d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brainexternalidentifier",
            index=models.Index(
                fields=["network", "namespace"], name="atlas_brain_network_fb0501_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brainexternalidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entity__isnull", False), ("network__isnull", True)),
                    models.Q(("entity__isnull", True), ("network__isnull", False)),
                    _connector="OR",
                ),
                name="ck_brain_external_id_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainexternalidentifier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("namespace")
                ),
                django.db.models.functions.text.Trim("identifier"),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("source_version")
                ),
                name="uq_brain_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="brainnetworkalias",
            index=models.Index(fields=["text"], name="atlas_brain_text_a10dc0_idx"),
        ),
        migrations.AddConstraint(
            model_name="brainnetworkalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("text")
                ),
                models.F("network"),
                models.F("language"),
                name="uq_brain_network_alias_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainnetworksource",
            constraint=models.UniqueConstraint(
                fields=("network", "source"), name="uq_brain_network_source"
            ),
        ),
    ]
