# Generated by Django 5.2.17 on 2026-09-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0033_v091_brain_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrainFunctionalAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("evidence_key", models.SlugField(max_length=180, unique=True)),
                ("source_version", models.CharField(max_length=120)),
                ("method", models.TextField()),
                ("limitations", models.TextField(blank=True)),
                ("task_context", models.TextField()),
                ("population_context", models.TextField()),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_functional_associations",
                        to="atlas.concept",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="functional_associations",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="functional_associations",
                        to="atlas.brainnetwork",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "evidence_key", "id"),
            },
        ),
        migrations.CreateModel(
            name="BrainFunctionalAssociationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.brainfunctionalassociation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_functional_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrainNetworkMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_fa", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("evidence_key", models.SlugField(max_length=180, unique=True)),
                ("source_version", models.CharField(max_length=120)),
                ("method", models.TextField()),
                ("limitations", models.TextField(blank=True)),
                ("qualifier", models.TextField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_memberships",
                        to="atlas.brainanatomicalentity",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anatomical_memberships",
                        to="atlas.brainnetwork",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "evidence_key", "id"),
            },
        ),
        migrations.CreateModel(
            name="BrainNetworkMembershipSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.brainnetworkmembership",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brain_membership_links",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="brainfunctionalassociation",
            index=models.Index(
                fields=["entity", "is_active", "review_status"],
                name="atlas_brain_entity__706910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brainfunctionalassociation",
            index=models.Index(
                fields=["network", "is_active", "review_status"],
                name="atlas_brain_network_8b66db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brainfunctionalassociation",
            index=models.Index(
                fields=["concept", "is_active", "review_status"],
                name="atlas_brain_concept_b49700_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainfunctionalassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entity__isnull", False), ("network__isnull", True)),
                    models.Q(("entity__isnull", True), ("network__isnull", False)),
                    _connector="OR",
                ),
                name="ck_brain_function_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainfunctionalassociationsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_brain_function_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="brainfunctionalassociationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("note", ""), _negated=True),
                name="ck_brain_function_source_note",
            ),
        ),
        migrations.AddIndex(
            model_name="brainnetworkmembership",
            index=models.Index(
                fields=["entity", "is_active", "review_status"],
                name="atlas_brain_entity__edcf1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brainnetworkmembership",
            index=models.Index(
                fields=["network", "is_active", "review_status"],
                name="atlas_brain_network_6551e4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="brainnetworkmembershipsource",
            constraint=models.UniqueConstraint(
                fields=("relationship", "source"), name="uq_brain_membership_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="brainnetworkmembershipsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("note", ""), _negated=True),
                name="ck_brain_membership_source_note",
            ),
        ),
    ]
