# Generated by Django 5.2.17 on 2026-09-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0034_v092_brain_relation_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="brainanatomicalalias",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("unreviewed", "Unreviewed"),
                    ("source_checked", "Source checked"),
                    ("reviewed", "Reviewed"),
                ],
                default="unreviewed",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="brainanatomicalalias",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_approval_links",
                to="atlas.sourcereference",
            ),
        ),
        migrations.AddField(
            model_name="brainanatomicalalias",
            name="source_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brainnetworkalias",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("unreviewed", "Unreviewed"),
                    ("source_checked", "Source checked"),
                    ("reviewed", "Reviewed"),
                ],
                default="unreviewed",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="brainnetworkalias",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_approval_links",
                to="atlas.sourcereference",
            ),
        ),
        migrations.AddField(
            model_name="brainnetworkalias",
            name="source_note",
            field=models.TextField(blank=True),
        ),
    ]
