# Generated by Django 5.2.17 on 2026-09-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0035_v092_brain_alias_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="brainexternalidentifier",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("unreviewed", "Unreviewed"),
                    ("source_checked", "Source checked"),
                    ("reviewed", "Reviewed"),
                ],
                default="unreviewed",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="brainexternalidentifier",
            name="source_note",
            field=models.TextField(blank=True),
        ),
    ]
