# Generated by Django 5.2.17 on 2026-10-07 15:22

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0036_v092_brain_identifier_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True, editable=False, max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=2000)),
                ("construct_overview", models.CharField(blank=True, max_length=1000)),
                ("rightsholder", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("name_en", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "review_status", "name_en"],
                        name="atlas_asses_is_acti_a7fb11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentLanguageForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("key", models.SlugField(max_length=120)),
                ("language", models.CharField(max_length=16)),
                ("label", models.CharField(max_length=255)),
                (
                    "form_kind",
                    models.CharField(
                        choices=[
                            ("original", "Original language form"),
                            ("translation", "Translation"),
                            ("adaptation", "Adaptation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=255)),
                (
                    "authorization_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Permission not established"),
                            ("authorized", "Authorization verified for this form"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("authorization_note", models.CharField(blank=True, max_length=1000)),
                (
                    "authorization_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_authorizations",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "key", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssessmentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("key", models.SlugField(max_length=180, unique=True)),
                (
                    "predicate",
                    models.CharField(
                        choices=[
                            ("measures", "Measures a construct"),
                            ("research_measure_of", "Research measure of a construct"),
                            ("screens_for", "Screens for"),
                            ("monitors", "Monitors severity/change"),
                            (
                                "diagnostic_support_for",
                                "One input in professional assessment",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("claim", models.CharField(max_length=1000)),
                ("context", models.CharField(max_length=1000)),
                ("limitations", models.CharField(max_length=1000)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_relations",
                        to="atlas.concept",
                    ),
                ),
                (
                    "disorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_relations",
                        to="atlas.disorder",
                    ),
                ),
                (
                    "language_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relations",
                        to="atlas.assessmentlanguageform",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_relations",
                        to="atlas.symptom",
                    ),
                ),
            ],
            options={
                "ordering": ("key", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssessmentValidationStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("key", models.SlugField(max_length=180, unique=True)),
                ("source_note", models.CharField(max_length=1000)),
                ("design", models.CharField(max_length=500)),
                ("population", models.CharField(max_length=500)),
                ("sample_context", models.CharField(max_length=1000)),
                ("sample_size", models.PositiveIntegerField(blank=True, null=True)),
                ("administration", models.CharField(max_length=500)),
                ("informant", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=1000)),
                ("comparator", models.CharField(blank=True, max_length=500)),
                ("limitations", models.CharField(max_length=1000)),
                (
                    "language_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_studies",
                        to="atlas.assessmentlanguageform",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_studies",
                        to="atlas.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ("key", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssessmentPsychometricEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("key", models.SlugField(max_length=180, unique=True)),
                (
                    "measurement_property",
                    models.CharField(
                        choices=[
                            ("reliability", "Reliability"),
                            ("validity", "Validity"),
                            ("responsiveness", "Responsiveness"),
                        ],
                        max_length=24,
                    ),
                ),
                ("statistic", models.CharField(max_length=120)),
                ("method", models.CharField(max_length=1000)),
                ("value_text", models.CharField(blank=True, max_length=80)),
                ("units", models.CharField(blank=True, max_length=120)),
                ("uncertainty", models.CharField(blank=True, max_length=500)),
                ("finding", models.CharField(max_length=2000)),
                ("limitations", models.CharField(max_length=1000)),
                ("extraction_locator", models.CharField(max_length=500)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="atlas.assessmentvalidationstudy",
                    ),
                ),
            ],
            options={
                "ordering": ("key", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssessmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("key", models.SlugField(max_length=120)),
                ("label", models.CharField(max_length=255)),
                (
                    "form_kind",
                    models.CharField(
                        choices=[
                            ("original", "Original form"),
                            ("revision", "Revision"),
                            ("short", "Short form"),
                            ("unknown", "Edition unresolved"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "publication_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("construct", models.CharField(blank=True, max_length=120)),
                (
                    "intended_use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("screening", "Screening"),
                            ("research", "Research measurement"),
                            ("severity", "Severity measurement"),
                            ("monitoring", "Monitoring"),
                            ("diagnostic_support", "Diagnostic support"),
                        ],
                        max_length=24,
                    ),
                ),
                ("administration", models.CharField(blank=True, max_length=500)),
                ("informant", models.CharField(blank=True, max_length=255)),
                ("population", models.CharField(blank=True, max_length=500)),
                ("limitations", models.CharField(blank=True, max_length=1000)),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_versions",
                        to="atlas.assessmentversion",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="atlas.assessmentinstrument",
                    ),
                ),
            ],
            options={
                "ordering": ("key", "id"),
            },
        ),
        migrations.AddField(
            model_name="assessmentvalidationstudy",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validation_studies",
                to="atlas.assessmentversion",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(max_length=1000)),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.assessmentinstrument",
                    ),
                ),
                (
                    "language_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.assessmentlanguageform",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.assessmentrelation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_claims",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="atlas.assessmentversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessmentrelation",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relations",
                to="atlas.assessmentversion",
            ),
        ),
        migrations.AddField(
            model_name="assessmentlanguageform",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="language_forms",
                to="atlas.assessmentversion",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("text", models.CharField(max_length=255)),
                (
                    "normalized_text",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("language", models.CharField(max_length=16)),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("name", "Alternative name"),
                            ("acronym", "Acronym"),
                            ("translated_title", "Translated display title"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_note", models.CharField(max_length=1000)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_aliases",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="atlas.assessmentinstrument",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="atlas.assessmentversion",
                    ),
                ),
            ],
            options={
                "ordering": ("language", "text", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssessmentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("source_checked", "Source checked"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("seed_managed", models.BooleanField(default=False)),
                ("key", models.SlugField(max_length=180, unique=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("questionnaire", "Questionnaire"),
                            ("manual", "Manual"),
                            ("translation", "Translation"),
                            ("metadata", "Metadata"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        choices=[
                            ("owner_access", "Owner access"),
                            ("redistribution", "Redistribution"),
                            ("metadata_listing", "Metadata listing"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(default="Not established", max_length=255),
                ),
                ("owner", models.CharField(blank=True, max_length=255)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("unknown", "Access not established"),
                            ("owner_access", "Available through owner"),
                            ("public_access", "Public access verified"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "license_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Permission not established"),
                            ("restricted", "Owner restrictions apply"),
                            (
                                "public_domain",
                                "Owner states public domain for this scope",
                            ),
                            (
                                "explicit_permission",
                                "Explicit permission for this scope",
                            ),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("terms", models.CharField(max_length=2000)),
                ("source_note", models.CharField(max_length=1000)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_access",
                        to="atlas.sourcereference",
                    ),
                ),
                (
                    "language_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_records",
                        to="atlas.assessmentlanguageform",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_records",
                        to="atlas.assessmentversion",
                    ),
                ),
            ],
            options={
                "ordering": ("key", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="assessmentversion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("key"),
                models.F("instrument"),
                name="uq_assessment_version_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("instrument__isnull", False),
                        ("language_form__isnull", True),
                        ("relation__isnull", True),
                        ("version__isnull", True),
                    ),
                    models.Q(
                        ("instrument__isnull", True),
                        ("language_form__isnull", True),
                        ("relation__isnull", True),
                        ("version__isnull", False),
                    ),
                    models.Q(
                        ("instrument__isnull", True),
                        ("language_form__isnull", False),
                        ("relation__isnull", True),
                        ("version__isnull", True),
                    ),
                    models.Q(
                        ("instrument__isnull", True),
                        ("language_form__isnull", True),
                        ("relation__isnull", False),
                        ("version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_assessment_source_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("instrument__isnull", False)),
                fields=("instrument", "source"),
                name="uq_assessment_source_instrument",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version__isnull", False)),
                fields=("version", "source"),
                name="uq_assessment_source_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("language_form__isnull", False)),
                fields=("language_form", "source"),
                name="uq_assessment_source_language_form",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation__isnull", False)),
                fields=("relation", "source"),
                name="uq_assessment_source_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("concept__isnull", False),
                        ("disorder__isnull", True),
                        ("symptom__isnull", True),
                    ),
                    models.Q(
                        ("concept__isnull", True),
                        ("disorder__isnull", True),
                        ("symptom__isnull", False),
                    ),
                    models.Q(
                        ("concept__isnull", True),
                        ("disorder__isnull", False),
                        ("symptom__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_assessment_relation_endpoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentlanguageform",
            constraint=models.UniqueConstraint(
                fields=("version", "language", "key"),
                name="uq_assessment_language_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version__isnull", True)),
                fields=("instrument", "normalized_text", "language"),
                name="uq_assessment_family_alias",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version__isnull", False)),
                fields=("version", "normalized_text", "language"),
                name="uq_assessment_version_alias",
            ),
        ),
    ]
