from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import dsm_views, views

urlpatterns = [
    path("auth/register/", views.RegisterView.as_view()),
    path("auth/login/", TokenObtainPairView.as_view()),
    path("auth/refresh/", TokenRefreshView.as_view()),
    path("auth/logout/", views.logout),
    path("auth/me/", views.me),

    path("categories/", views.categories),
    path("disorders/", views.DisorderListView.as_view()),
    path("disorders/compare/", views.compare_disorders),
    path("disorders/<slug:slug>/", views.DisorderDetailView.as_view()),

    path("quizzes/", views.QuizListView.as_view()),
    path("quizzes/<slug:slug>/", views.QuizDetailView.as_view()),
    path("quizzes/<slug:slug>/submit/", views.quiz_submit),

    path("cases/", views.ClinicalCaseListView.as_view()),
    path("cases/<slug:slug>/", views.ClinicalCaseDetailView.as_view()),
    path("cases/<slug:slug>/submit/", views.case_submit),
    path("cases/<slug:slug>/attempts/", views.case_attempt_start),
    path("cases/<slug:slug>/attempts/current/", views.case_attempt_current),
    path("case-attempts/<int:attempt_id>/", views.case_attempt_detail),
    path("case-attempts/<int:attempt_id>/decisions/", views.case_attempt_decision),
    path("case-analytics/overview/", views.case_analytics_overview),
    path("case-analytics/cases/<slug:slug>/", views.case_analytics_detail),

    path("bookmarks/", views.bookmarks),
    path("bookmarks/<slug:slug>/", views.bookmark_delete),
    path("progress/<slug:slug>/view/", views.progress_view),
    path("notes/", views.notes),
    path("notes/<slug:slug>/", views.note_detail),
    path("dashboard/", views.dashboard),

    path("concepts/", views.ConceptListView.as_view()),
    path("concepts/<slug:slug>/", views.ConceptDetailView.as_view()),
    path("concepts/<slug:slug>/view/", views.concept_view),
    path("concepts/<slug:slug>/neighborhood/", views.concept_neighborhood),
    path("concept-bookmarks/", views.concept_bookmarks),
    path("concept-bookmarks/<slug:slug>/", views.concept_bookmark_delete),
    path("concept-notes/", views.concept_notes),
    path("concept-notes/<slug:slug>/", views.concept_note_detail),
    path("flashcards/", views.FlashcardListView.as_view()),
    path("flashcards/review-queue/", views.review_queue),
    path("flashcards/<slug:slug>/review/", views.flashcard_review),
    path("daily-challenge/", views.daily_challenge),
    path("study/overview/", views.study_overview),
    path("search/", views.global_search),
    path("atlas-overview/", views.atlas_overview),
    path("concept-map/", views.concept_map),
    path("concept-map/path/", views.graph_path),
    path("cognitive-distortions/overview/", views.cognitive_distortions_overview),
    path("cognitive-distortions/practice/", views.distortion_practice_queue),
    path("cognitive-distortions/practice/<slug:slug>/submit/", views.distortion_practice_submit),

    path("therapies/", views.TherapyListView.as_view()),
    path("therapies/taxonomy/", views.therapy_taxonomy),
    path("therapies/compare/", views.compare_therapies),
    path("therapies/<slug:slug>/", views.TherapyDetailView.as_view()),
    path("therapy-bookmarks/", views.therapy_bookmarks),
    path("therapy-bookmarks/<slug:slug>/", views.therapy_bookmark_delete),
    path("therapy-notes/", views.therapy_notes),
    path("therapy-notes/<slug:slug>/", views.therapy_note_detail),
    path("techniques/", views.TechniqueListView.as_view()),
    path("techniques/<slug:slug>/", views.TechniqueDetailView.as_view()),

    path("psychologists/", views.PsychologistListView.as_view()),
    path("psychologists/<slug:slug>/", views.PsychologistDetailView.as_view()),
    path("theories/", views.TheoryListView.as_view()),
    path("theories/<slug:slug>/", views.TheoryDetailView.as_view()),
    path("timeline/", views.TimelineEventListView.as_view()),
    path("timeline/<slug:slug>/", views.TimelineEventDetailView.as_view()),

    path("dsm/overview/", dsm_views.dsm_overview),
    path("dsm/metadata/", dsm_views.dsm_metadata),
    path("dsm/study-kit/", dsm_views.dsm_study_kit),
    path("dsm/graph/", dsm_views.dsm_graph),
    path("dsm/records/", dsm_views.DSMRecordListView.as_view()),
    path("dsm/records/by-disorder/<slug:slug>/", dsm_views.dsm_record_by_disorder),
    path("dsm/records/<str:master_id>/", dsm_views.DSMRecordDetailView.as_view()),
]
